### ISSUE TITLE
pgpre.sh: wrong return code when wrong PostgreSQL Version

### ISSUE THREAD

**Issue by viteisele** [cybertec-postgresql/safe-backup#2]
The return code of pgpre.sh is sometimes wrong, e. g. when the script is started with PostgreSQL V14:

postgres> pgpre.sh
FEHLER:  Funktion pg_backup_start(unknown, boolean) existiert nicht
ZEILE 1: SELECT pg_backup_start('pitr_sicherung', FALSE);
                ^
TIP:  Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.
backup starting location:
postgres> echo $?
0

The expected value is 1

**Comment by laurenz** [comment]
Before PostgreSQL v15, the functions are called `pg_start_backup()` and `pg_stop_backup()`.
You have to edit the scripts to use them with old PostgreSQL versions.

The reason for that change was that the function has changed semantics. So you have to replace

```
pg_backup_start('pitr_sicherung', FALSE)
```

with

```
pg_start_backup('pitr_sicherung', FALSE, FALSE)
```

**Comment by viteisele** [comment]
You are right: for PostgreSQL 14 pg_start_backup has to be used.
And later pg_stop_backup in the script, of course.

But why the return code is 0 with pg_backup_start, which means that the skript was executed successfully ?

**Comment by laurenz** [comment]
Ah, you are right. I need to check one more return code.

**Comment by viteisele** [comment]
Thank you, now it works as expected :-)

**Comment by laurenz** [comment]
Thanks for the report!
